### ISSUE TITLE
How to create a new shared database from client site

### ISSUE THREAD

**Issue by OnnoGeorg** [colinskow/superlogin#108]
I am using SuperLogin in a Ionic 2 test app connected to a remote CouchDB server. Creating new users with synchronized local and remote private user databases is running very well. But now I want to add  new databases, which are shared between some of the users. These databases should be created from client site after some user action in the app.

Since the private user databases are created through SuperLogin, also the creation of shared databases should, in principle, be possible. Is there a way to do this through SuperLogin?

**Comment by chriseyhorn** [comment]
@OnnoGeorg 
I'm doing this using the addUserDB call and passing in 'shared'.  You can do this for each user to be added to the shared db by using the same db name and passing in their id.

superlogin.addUserDB('user1', 'sharedDBname', 'shared', ['docs'], ['roles']);
superlogin.addUserDB('user2', 'sharedDBname', 'shared', ['docs'], ['roles']);

This will only add the 'sharedDBname' once and add the db to the user's doc in the user db.

Since this call is specific to superlogin, I setup a route in my express app that is called from the client that in turn makes the call.

**Comment by OnnoGeorg** [comment]
Thanks, @chriseyhorn. At the time of my question, I did not know that `addUserDB()` not only adds a database to a user but also creates this database if it does not exist. I came up with a quite complicated workaround, but your solution with a route directly in express is much cleaner, thanks also for this. I will close this issue.
