### ISSUE TITLE
forgot-password fails if loginOnPasswordReset: true

### ISSUE THREAD

**Issue by tonydiep** [colinskow/superlogin#189]
ISSUE
Superlogin fails with 'Unhandled rejection TypeError: user.createSession is not a function'
on
POST /password-reset
if
// If set to true, the user will be logged in automatically after resetting the password
    loginOnPasswordReset: true

WORKAROUND
Set loginOnPasswordReset: false

SUPERLOGIN VERSION PER PACKAGE.JSON
"superlogin": "^0.6.1"

**Comment by clariontools** [comment]
@tonydiep - The NPM has not been updated in quite a while, this issue and others have been fixed in the github repo, to get the fixes you will need to pull the version directly from the repo :yum: 

You can edit the superlogin package.json directly with "superlogin": "colinskow/superlogin#commit_hash" **_which as of October 22, 2017 would look like:_**

`    "superlogin": "colinskow/superlogin#8e7c7c1a77c1f5303b74f941208349e3a6e0c9ad",`

Then you need to do npm install, you can also do everything from the command line with a --save to update the package.json with npm install --save colinskow/superlogin#commit_hash, which would look like below using the **_current master as of October 22, 2017:_**

`npm install --save colinskow/superlogin#8e7c7c1a77c1f5303b74f941208349e3a6e0c9ad`

Just remember you then own the version of superlogin and if the npm package is ever updated you will want to make changes or update to get the latest directly from the npm configuration.  Good luck and post back here to confirm the fix and close the issue.

**Comment by tonydiep** [comment]
Thanks for the quick reply and the instructions for using the github repo. I'm going to stick with the npm version as I don't have the skills to maintain my own version of superlogin. Can I ask if there are plans to update the npm version?

**Comment by clariontools** [comment]
@tonydiep - There is not much more to maintain by pointing to the repo directly, just that one line in the package.json.

> Can I ask if there are plans to update the npm version?

Updates are controlled by the owner of this repo @colinskow , so he would be the only one to answer for sure.  I wouldn't expect anything until there is official word from Colin, who most recently commented that he was busy on other projects.
