### ISSUE TITLE
Add more session adapter

### ISSUE THREAD

**Issue by micky2be** [colinskow/superlogin#54]
Would be nice to be able to configure a different session adapter other than Redis or memory.

We are not sure we gonna use Redis for our project, so now we are stuck with using the memory adapter but like you can imagine this is far from being ideal.

**Comment by micky2be** [comment]
Even for development purpose, saving the session in file might be slightly better then memory.
At least the session would be able to persist.

**Comment by colinskow** [comment]
Thank you for PR #57

**Comment by colinskow** [comment]
Merged #57 Closing

**Comment by ichagas** [comment]
It sounds like expensive $1,450/mo for up to 5,000 connections on Heroku Redis. Any idea what does it means in the real world?

I am considering to use Superlogin for auth PouchDB <-> Cloudant since [PouchDB Authentication](https://github.com/nolanlawson/pouchdb-authentication/pull/23#issuecomment-83530512) is not Cloudant compatible.

But I see a _risk_ to receive a large $$ bill to pay if the App get about **30K users** or so. Of corse, I can run my own Redis Server but I prefer a _Backendless_ approach this is why PouchDB/Cloudant approach.

**Comment by colinskow** [comment]
@ichagas you can use whatever Redis service you want with Heroku, including Amazon. Just plug in the access credentials to the correct environment variables. You can see [superlogin-demo](https://github.com/colinskow/superlogin-demo) for an example.

Redis usage is extremely light, and I think you could expand quite a bit using the free version. One Heroku client only uses one connection. Each session is less than 500 bytes of info.

In my experience the Cloudant bill is what you have to worry about with lots of users.

**Comment by DimShadoWWW** [comment]
@ichagas I was adding etcd and firebase as backend (in my fork) .. but haven't test it yet

**Comment by ichagas** [comment]
@DimShadoWWW, let me know when you have time to test the Firebase version, sounds a good idea.

@colinskow, as I understood, **superlogin** will use only one Redis connection no matter what is the number of users?
Btw, 👍 thanks for your insides on the Cloudant. I am going to review this decision and prepare a plan B to implement as soon as the App launch. Perhaps use DigitalOcean for CouchDB+Redis could be cheaper solution. Anyhow, I am moving on now and review it later.

Thanks.

**Comment by DimShadoWWW** [comment]
@ichagas :+1:
