### ISSUE TITLE
Feature Request: Support mongoDB and PostgreSQL

### ISSUE THREAD

**Issue by robotiko** [colinskow/superlogin#9]
Hi, 
Is there any plan to support additional DBs?

Thxs

**Comment by colinskow** [comment]
Thank you very much for your interest. Unlike other databases CouchDB allows easy data replication to client devices and allows end-users to authenticate directly with the DB, which saves traffic on the backend. About 80% of SuperLogin's code is dedicated to managing authentication across multiple CouchDB databases, so it wouldn't be practical to port it.

[MEAN.io](http://mean.io) has much of the same functionality for MongoDB. SQL is more difficult since it doesn't allow nested data and would require complex joins. [Lockit](https://github.com/zemirco/lockit) provides some basic functionality there.

You are more than welcome to fork the project and adapt it to Mongo. It wouldn't be that difficult as most of the code is for supporting CouchDB per-user databases.

**Comment by robotiko** [comment]
Thanks a lot @colinskow.
Now I have a clear picture of couchDB dependency. 
As you pointed, in that case there are some other options. 

I will close. 

Thanks
